'use client';
import { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'ES' | 'EN';

const dictionary = {
  ES: {
    // HOME
    accessControl: "Control de Acceso",
    operatorId: "ID Operador...",
    accessCode: "Código de acceso...",
    enter: "Entrar",
    active: "Activo",
    iaExpert: "IA Experta (Manuales)",
    iaExpertDesc: "Asistente de Superinteligencia basado en los manuales oficiales de tu empresa. Resuelve dudas operativas en base a conocimiento guardado.",
    openChat: "Abrir Chat",
    comingSoon: "Próximamente",
    iaPlant: "IA Planta (Conexión PLC)",
    iaPlantDesc: "Monitoreo analítico predictivo en tiempo real conectado a sensores. Detecta posibles fallas y anomalías en las máquinas de forma autónoma.",
    inDevelopment: "En desarrollo...",
    footer: "© 2026 Azteq-IA. Sistema Operacional de Nueva Generación.",
    
    // CHAT
    returnBtn: "Retornar",
    expertBadge: "Azteq-IA Experto",
    hello: "¡Hola! Soy tu IA de Superinteligencia",
    helloDesc: "Pregúntame sobre los manuales técnicos guardados en nuestra base de datos. Si no encuentro la información exacta, usaré mi conocimiento general para ayudarte.",
    thinking: "Pensando...",
    placeholder: "Pregunta algo técnico (Ej: ¿A qué temperatura se calibra la XYZ-120?)...",
    send: "Enviar",
    errorCon: "⚠ Fallo al conectar con la API de chat.",

    // PLANTA [brand]/page.tsx
    plDisconnect: "Desconectar",
    plBackToBrands: "Volver a Marcas",
    plControlCenter: "Control Central",
    plPlcConnection: "Conexión PLC",
    plDashboard: "Dashboard",
    plRitualLink: "Enlace Ritual",
    plConnectingTo: "Conectando ofrenda a",
    plLocalMode: "Templo Reliquia (Local)",
    plCloudMode: "Cielo Puro (VPN)",
    plSelectPlc: "Seleccionar Reliquia / Conexión Nueva",
    plNewConnection: "-- Crear Nueva Conexión --",
    plConnectionPaths: "Sendas de Conexión",
    plLocalModeDesc: "La ofrenda (equipo Azteq-IA) se hace en el mismo suelo sagrado (LAN) que el",
    plCloudModeDesc: "La comunicación viaja por los vientos a través de un túnel místico (VPN) que proveen los guardianes de red.",
    plReadMore: "Leer más: Guía completa de conexión paso a paso",
    plControllerFamily: "Familia / Protocolo del Controlador",
    plVpnNote: "La IP debe pertenecer al túnel cifrado (VPN), no a la aldea local (LAN) de la fábrica.",
    plIpLocal: "IP de Ofrenda (LAN)",
    plIpVpn: "IP de Túnel (VPN)",
    plPortLabel: "Puerta de Acceso (Puerto)",
    plRackLabel: "Nivel (Rack)",
    plSlotLabel: "Piedra (Slot)",
    plConnecting: "INVOCANDO...",
    plConnect: "REALIZAR ENLACE",
    plRealTimeMonitoring: "MONITOREO EN TIEMPO REAL",
    plConnectionStatus: "Estado Conexión",
    plCpuTemp: "Temperatura CPU",
    plSystemPressure: "Presión Sistema",
    plGeneralStatus: "Estatus General",
    plCyclesPerHour: "Ciclos / Hora",
    plAccessError: "⚠ Error de Acceso PLC",
    plPredictiveAlarm: "Alarma Predictiva",
    plAllNormal: "no presenta anomalías en la última lectura. Todo rinde al 98% de su capacidad.",
    plAdjustIO: "Ajustar E/S",
    plSaveName: "Nombre para guardar...",
    plSave: "GUARDAR",
    plLiveAssistant: "Asistente en vivo conectado a",
    plAiGreeting: "Hola. Soy la IA de Azteq conectada a",
    plAiGreetingEnd: ". ¿En qué puedo ayudarte?",
    plAnalyzing: "Analizando...",
    plChatPlaceholder: "Pregunta sobre el sistema",
    plVarMapper: "Mapeador Libre de Variables",
    plHideHelp: "Ocultar Ayuda",
    plHowItWorks: "¿Cómo funciona?",
    plNewSignal: "Vincular Nueva Señal del PLC",
    plGroupCol: "Grupo/Rutina",
    plLabelCol: "Etiqueta Lógica",
    plAddressCol: "Dirección",
    plUnitCol: "Unidad",
    plDataTypeCol: "Tipo Dato",
    plActionCol: "Acción",
    plNoMappings: "[ SIN MAPEOS ENCONTRADOS ]",
    plAddVarsHint: "Añade variables arriba para iniciar el gemelo digital.",
    plCancel: "Cancelar",
    plSaveMap: "Sellar y Guardar Mapa",

    // /planta/page.tsx
    piBack: "← Volver",
    piHelp: "Ayuda",
    piIaPlanta: "IA Planta",
    piOpenDashboard: "Abrir Visión Global (Dashboard)",
    piSelectPLC: "Selecciona el PLC",
    piSelectPLCDesc: "Elige la marca del controlador lógico programable al que la IA Planta deberá conectarse y analizar de forma individual.",
    piIndustrialConnection: "Conexión Industrial",

    // /planta/dashboard/page.tsx
    dbBackToBrands: "← Volver a Marcas",
    dbVisionTitle: "Visión del Imperio",
    dbProductionGroups: "Líneas / Grupos de Producción",
    dbGroupNamePlaceholder: "Nombre de la línea o grupo",
    dbSaveChanges: "Guardar Cambios",
    dbCreateGroup: "Crear Grupo",
    dbCancel: "Cancelar",
    dbLoading: "Cargando...",
    dbNoGroups: "No hay grupos creados.",
    dbEdit: "Editar",
    dbDelete: "Eliminar",
    dbNoGroup: "Sin Grupo",
    dbInspect: "Inspeccionar",
    dbShowVars: "Ver Variables",
    dbHideVars: "Ocultar Variables",
    dbVariables: "Variables",
    dbColName: "Nombre",
    dbColValue: "Valor",
    dbNoVars: "Sin variables disponibles",
    dbGlobalVision: "Visión Global",
    dbGlobalVisionDesc: "Monitoreo panóptico de reliquias y nodos sincronizados en tiempo real",
    dbNoPlcs: "Sin Reliquias Conectadas",
    dbNoPlcsDesc: "Todavía no hay conexiones físicas con equipos industriales. Solo los usuarios administradores pueden visualizar la maqueta de simulación.",
    dbAlertsTitle: "Registro de Alertas y Anomalías",
    dbColTime: "Hora",
    dbColEquip: "Equipo/Nodo",
    dbColCode: "Código",
    dbColDesc: "Descripción",
    dbColSeverity: "Severidad",
    dbClearErrors: "Borrar todos los errores",
    dbResolved: "Resuelto",
    dbConfirmDelete: "¿Seguro que deseas borrar este PLC? Esta acción es permanente y no se puede deshacer.",
    dbConfirmClearErrors: "¿Seguro que deseas borrar todos los errores? Esta acción no se puede deshacer.",
    dbConfirmDeleteGroup: "¿Eliminar este grupo/linea?",
  },
  EN: {
    // HOME
    accessControl: "Access Control",
    operatorId: "Operator ID...",
    accessCode: "Access Code...",
    enter: "Enter",
    active: "Active",
    iaExpert: "Expert AI (Manuals)",
    iaExpertDesc: "Superintelligence Assistant based on your company's official manuals. Solves operational doubts using stored knowledge.",
    openChat: "Open Chat",
    comingSoon: "Coming Soon",
    iaPlant: "Plant AI (PLC Connection)",
    iaPlantDesc: "Real-time predictive analytical monitoring connected to sensors. Autonomously detects possible machine faults and anomalies.",
    inDevelopment: "In development...",
    footer: "© 2026 Azteq-IA. Next Generation Operational System.",

    // CHAT
    returnBtn: "Return",
    expertBadge: "Azteq-IA Expert",
    hello: "Hello! I am your Superintelligence AI",
    helloDesc: "Ask me about the technical manuals stored in our database. If I can't find the exact information, I will use my general knowledge to help you.",
    thinking: "Thinking...",
    placeholder: "Ask something technical (e.g., At what temp is the XYZ-120 calibrated?)...",
    send: "Send",
    errorCon: "⚠ Failed to connect to the chat API.",

    // PLANTA [brand]/page.tsx
    plDisconnect: "Disconnect",
    plBackToBrands: "Back to Brands",
    plControlCenter: "Control Center",
    plPlcConnection: "PLC Connection",
    plDashboard: "Dashboard",
    plRitualLink: "Link Setup",
    plConnectingTo: "Connecting to",
    plLocalMode: "Local Network (LAN)",
    plCloudMode: "Cloud Tunnel (VPN)",
    plSelectPlc: "Select Saved Device / New Connection",
    plNewConnection: "-- Create New Connection --",
    plConnectionPaths: "Connection Paths",
    plLocalModeDesc: "The Azteq-IA device connects on the same local network (LAN) as the",
    plCloudModeDesc: "Communication travels through an encrypted VPN tunnel provided by the network administrators.",
    plReadMore: "Read more: Step-by-step connection guide",
    plControllerFamily: "Controller Family / Protocol",
    plVpnNote: "The IP must belong to the encrypted VPN tunnel, not the factory's local network (LAN).",
    plIpLocal: "Device IP (LAN)",
    plIpVpn: "Tunnel IP (VPN)",
    plPortLabel: "Access Port",
    plRackLabel: "Level (Rack)",
    plSlotLabel: "Slot",
    plConnecting: "CONNECTING...",
    plConnect: "ESTABLISH LINK",
    plRealTimeMonitoring: "REAL-TIME MONITORING",
    plConnectionStatus: "Connection Status",
    plCpuTemp: "CPU Temperature",
    plSystemPressure: "System Pressure",
    plGeneralStatus: "General Status",
    plCyclesPerHour: "Cycles / Hour",
    plAccessError: "⚠ PLC Access Error",
    plPredictiveAlarm: "Predictive Alarm",
    plAllNormal: "shows no anomalies in the last reading. Running at 98% capacity.",
    plAdjustIO: "Adjust I/O",
    plSaveName: "Name to save...",
    plSave: "SAVE",
    plLiveAssistant: "Live assistant connected to",
    plAiGreeting: "Hello. I am Azteq's AI connected to",
    plAiGreetingEnd: ". How can I help you?",
    plAnalyzing: "Analyzing...",
    plChatPlaceholder: "Ask about the",
    plVarMapper: "Free Variable Mapper",
    plHideHelp: "Hide Help",
    plHowItWorks: "How does it work?",
    plNewSignal: "Link New PLC Signal",
    plGroupCol: "Group/Routine",
    plLabelCol: "Logical Tag",
    plAddressCol: "Address",
    plUnitCol: "Unit",
    plDataTypeCol: "Data Type",
    plActionCol: "Action",
    plNoMappings: "[ NO MAPPINGS FOUND ]",
    plAddVarsHint: "Add variables above to start the digital twin.",
    plCancel: "Cancel",
    plSaveMap: "Seal & Save Map",

    // /planta/page.tsx
    piBack: "← Back",
    piHelp: "Help",
    piIaPlanta: "Plant AI",
    piOpenDashboard: "Open Global Vision (Dashboard)",
    piSelectPLC: "Select PLC",
    piSelectPLCDesc: "Choose the manufacturer of the programmable logic controller the Plant AI should connect to and analyze individually.",
    piIndustrialConnection: "Industrial Connection",

    // /planta/dashboard/page.tsx
    dbBackToBrands: "← Back to Brands",
    dbVisionTitle: "Empire Vision",
    dbProductionGroups: "Production Lines / Groups",
    dbGroupNamePlaceholder: "Line or group name",
    dbSaveChanges: "Save Changes",
    dbCreateGroup: "Create Group",
    dbCancel: "Cancel",
    dbLoading: "Loading...",
    dbNoGroups: "No groups created.",
    dbEdit: "Edit",
    dbDelete: "Delete",
    dbNoGroup: "No Group",
    dbInspect: "Inspect",
    dbShowVars: "Show Variables",
    dbHideVars: "Hide Variables",
    dbVariables: "Variables",
    dbColName: "Name",
    dbColValue: "Value",
    dbNoVars: "No variables available",
    dbGlobalVision: "Global Vision",
    dbGlobalVisionDesc: "Panoptic monitoring of synced devices and nodes in real time",
    dbNoPlcs: "No Connected Devices",
    dbNoPlcsDesc: "No physical connections with industrial equipment yet. Only admin users can view the simulation mockup.",
    dbAlertsTitle: "Alerts & Anomalies Log",
    dbColTime: "Time",
    dbColEquip: "Device/Node",
    dbColCode: "Code",
    dbColDesc: "Description",
    dbColSeverity: "Severity",
    dbClearErrors: "Clear all errors",
    dbResolved: "Resolved",
    dbConfirmDelete: "Are you sure you want to delete this PLC? This action is permanent and cannot be undone.",
    dbConfirmClearErrors: "Are you sure you want to clear all errors? This action cannot be undone.",
    dbConfirmDeleteGroup: "Delete this group/line?",
  }
};

type ContextType = {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: typeof dictionary['ES'];
};

const LanguageContext = createContext<ContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('ES');
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: dictionary[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
