'use client';
import { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'ES' | 'EN';

const dictionary = {
  ES: {
    // HOME
    activeSession: "Sesión Activa",
    planWord: "PLAN",
    operatorLabel: "Operador:",
    adminPanel: "Panel Admin",
    changePlan: "Cambiar Plan",
    logout: "Cerrar Sesión",
    infoBtn: "Info",
    freeAccessBadge: "✓ ACCESO LIBRE",
    requiresProBadge: "🔒 REQUIERE PRO",
    enterChat: "Entrar al Chat →",
    enterControl: "Entrar a Control →",
    loginAbove: "Inicia sesión ↑",
    accessControl: "Control de Acceso",
    operatorId: "ID Operador...",
    accessCode: "Código de acceso...",
    emailAddress: "Correo electronico...",
    password: "Contraseña...",
    enter: "Entrar",
    register: "Registrarse",
    registering: "Registrando...",
    registerNow: "Crear Cuenta",
    hasAccount: "¿Ya tienes cuenta?",
    backToLogin: "Regresar al inicio de sesión",
    loginError: "⚠ Correo o contraseña incorrectos.",
    registerError: "⚠ Error al registrar cuenta.",
    active: "Activo",
    loginTitle: "Iniciar Sesión",
    forgotPassword: "¿Olvidaste tu contraseña?",
    choosePlan: "Elige tu Plan",
    choosePlanDesc: "Selecciona la suscripción que mejor se adapte a tus necesidades para acceder al sistema.",
    planBasicAccess: "Acceso a la IA Experta",
    planBasicLimit: "Límite de 20 preguntas al día",
    startFree: "Comenzar Gratis",
    planProAccess: ["Acceso", "ilimitado", "a la IA Experta"],
    planProPlcs: ["Conectar hasta", "2 PLCs", "en IA Planta"],
    planProSupport: "Soporte prioritario",
    subscribe: "Suscribirme",
    freeAccessPlan: "Acceso Libre",
    planEntAccess: ["Acceso", "total e ilimitado", "al sistema"],
    planEntPlcs: ["Conectar", "PLCs ilimitados", ""],
    fullAccess: "Acceso Total",
    registerOperator: 'Registro de Operador',
    operatorName: 'Nombre de Operador',
    operatorNamePlaceholder: 'Ej. Juan P.',
    registerAction: 'Registrar',
    backToHome: 'Volver al Inicio',
    fillAllFields: 'Por favor llena todos los campos.',
    passwordRequirements: 'La contraseña debe tener al menos 6 caracteres (incluyendo números), 1 mayúscula y 1 símbolo especial (#$%&).',
    redirecting: 'Redirigiendo al sistema...',
    emailPlaceholder: 'operador@ejemplo.com',
    passwordPlaceholder: '6 caracteres, 1 número, 1 mayú, 1 símbolo',
    iaExpert: "IA Experta (Manuales)",
    iaExpertDesc: "Asistente de Superinteligencia basado en los manuales oficiales de tu empresa. Resuelve dudas operativas en base a conocimiento guardado.",
    openChat: "Abrir Chat",
    comingSoon: "Próximamente",
    iaPlant: "IA Planta (Conexión PLC)",
    iaPlantDesc: "Monitoreo analítico predictivo en tiempo real conectado a sensores. Detecta posibles fallas y anomalías en las máquinas de forma autónoma.",
    inDevelopment: "En desarrollo...",
    footer: "© 2026 Azteq-IA. Sistema Operacional de Nueva Generación.",
    
    // INFO MODAL
    infoTooltip: "¿Qué hace cada IA?",
    iaExpertSubtitle: "Asistente Técnico (RAG)",
    iaExpertFeat1: "Zero Alucinaciones:",
    iaExpertFeat1Desc: "Respuestas 100% confiables basadas exclusivamente en *tus* manuales y diagramas (PDF/TXT). Soluciona tus problemas con total seguridad.",
    iaExpertFeat2: "Dispara tu OEE (Downtime Killer):",
    iaExpertFeat2Desc: "Olvida las horas buscando en papel. Diagnostica y resuelve fallas complejas en segundos, aumentando tu Disponibilidad Pura hasta un 40%.",
    iaExpertFeat3: "Experto Matemático Integrado:",
    iaExpertFeat3Desc: "Cálculos de calibración avanzados e ingeniería de control resueltos al instante de forma precisa.",
    iaPlantSubtitle: "Monitoreo IoT & Gemelo Digital",
    iaPlantFeat1: "Conecta con Cualquier PLC:",
    iaPlantFeat1Desc: "Compatibilidad nativa sin pagar licencias extras. Enlaza equipos Siemens, Modbus o Allen-Bradley en cuestión de clics.",
    iaPlantFeat2: "Crece a tu Ritmo:",
    iaPlantFeat2Desc: "Desde automatizar una sola máquina hasta tener una flotilla multimarca en tu gemelo digital. Se adapta perfecto a tu presupuesto.",
    iaPlantFeat3: "Tu Planta en tu Bolsillo:",
    iaPlantFeat3Desc: "Dashboards gerenciales en vivo. Monitorea KPIs críticos (presiones, cuellos de botella) desde tu celular o tablet en cualquier parte del mundo.",
    
    // PLANES
    planesTitle: "Actualiza tu Plan",
    planesDesc: "Selecciona la suscripción que mejor se adapte a tus necesidades. Las actualizaciones se aplican de manera inmediata a tu cuenta.",
    backBtn: "Volver",
    subscriptions: "SUSCRIPCIONES",
    monthly: "Facturación Mensual",
    annual: "Facturación Anual",
    save10: "Ahorra 10%",
    currentPlan: "Tu Plan Actual",
    recommended: "Recomendado",
    basicPlan: "Básico",
    proPlan: "Profesional",
    enterprisePlan: "Enterprise",
    perMonth: "USD /mes",
    billedAnnually: "USD facturados al año",
    unlockPro: "Desbloquear Plan Pro \u2192",
    contactSales: "Contactar Ventas",
    upgradePro: "Subir a Pro",
    buyEnterprise: "Adquirir Enterprise",
    checkoutTitle: "Finalizar Compra",
    checkoutDesc: "Estás a un paso de activar tu suscripción",
    totalToday: "Total a pagar hoy",
    paySecure: "Pagar de forma Segura",
    connectingTerminal: "Conectando con terminal de pago...",
    retryPayment: "Reintentar Pago",
    paymentFailed: "Pago Rechazado",
    paymentErrorDesc: "Lo sentimos, la conexión de pago falló o la tarjeta fue rechazada. Por favor, intenta de nuevo o comunícate con soporte.",
    
    // CHAT
    newChat: "Nuevo Chat",
    viewChats: "Ver Chats",
    returnBtn: "Retornar",
    expertBadge: "Azteq-IA Experto",
    hello: "¡Hola! Soy tu IA de Superinteligencia",
    helloDesc: "",
    thinking: "Pensando...",
    placeholder: "Pregunta lo que quieras...",
    send: "Enviar",
    errorCon: "⚠ Fallo al conectar con la API de chat.",
    noRecentChats: "Sin chats recientes",
    attachImage: "Adjuntar imagen",

    // PLANTA [brand]/page.tsx
    plDisconnect: "Desconectar",
    plBackToBrands: "Volver a Marcas",
    plControlCenter: "Control Central",
    plPlcConnection: "Conexión PLC",
    plDashboard: "Dashboard",
    plRitualLink: "Enlace Ritual",
    plConnectingTo: "Conectando ofrenda a",
    plLocalMode: "Templo Reliquia (Local)",
    plCloudMode: "Cielo Puro (VPN)",
    plSelectPlc: "Seleccionar Reliquia / Conexión Nueva",
    plNewConnection: "-- Crear Nueva Conexión --",
    plConnectionPaths: "Sendas de Conexión",
    plLocalModeDesc: "La ofrenda (equipo Azteq-IA) se hace en el mismo suelo sagrado (LAN) que el",
    plCloudModeDesc: "La comunicación viaja por los vientos a través de un túnel místico (VPN) que proveen los guardianes de red.",
    plReadMore: "Leer más: Guía completa de conexión paso a paso",
    plControllerFamily: "Familia / Protocolo del Controlador",
    plVpnNote: "La IP debe pertenecer al túnel cifrado (VPN), no a la aldea local (LAN) de la fábrica.",
    plIpLocal: "IP de Ofrenda (LAN)",
    plIpVpn: "IP de Túnel (VPN)",
    plPortLabel: "Puerta de Acceso (Puerto)",
    plRackLabel: "Nivel (Rack)",
    plSlotLabel: "Piedra (Slot)",
    plConnecting: "INVOCANDO...",
    plConnect: "REALIZAR ENLACE",
    plRealTimeMonitoring: "MONITOREO EN TIEMPO REAL",
    plConnectionStatus: "Estado Conexión",
    plCpuTemp: "Temperatura CPU",
    plSystemPressure: "Presión Sistema",
    plGeneralStatus: "Estatus General",
    plCyclesPerHour: "Ciclos / Hora",
    plAccessError: "⚠ Error de Acceso PLC",
    plPredictiveAlarm: "Alarma Predictiva",
    plAllNormal: "no presenta anomalías en la última lectura. Todo rinde al 98% de su capacidad.",
    plAdjustIO: "Ajustar E/S",
    plSaveName: "Nombre para guardar...",
    plSave: "GUARDAR",
    plLiveAssistant: "Asistente en vivo conectado a",
    plAiGreeting: "Hola. Soy la IA de Azteq conectada a",
    plAiGreetingEnd: ". ¿En qué puedo ayudarte?",
    plAnalyzing: "Analizando...",
    plChatPlaceholder: "Pregunta sobre el sistema",
    plVarMapper: "Mapeador Libre de Variables",
    plHideHelp: "Ocultar Ayuda",
    plHowItWorks: "¿Cómo funciona?",
    plNewSignal: "Vincular Nueva Señal del PLC",
    plGroupCol: "Grupo/Rutina",
    plLabelCol: "Etiqueta Lógica",
    plAddressCol: "Dirección",
    plUnitCol: "Unidad",
    plDataTypeCol: "Tipo Dato",
    plActionCol: "Acción",
    plNoMappings: "[ SIN MAPEOS ENCONTRADOS ]",
    plAddVarsHint: "Añade variables arriba para iniciar el gemelo digital.",
    plCancel: "Cancelar",
    plSaveMap: "Sellar y Guardar Mapa",

    // /planta/page.tsx
    piBack: "← Volver",
    piHelp: "Ayuda",
    piIaPlanta: "IA Planta",
    piOpenDashboard: "Abrir Visión Global (Dashboard)",
    piSelectPLC: "Selecciona el PLC",
    piSelectPLCDesc: "Elige la marca del controlador lógico programable al que la IA Planta deberá conectarse y analizar de forma individual.",
    piIndustrialConnection: "Conexión Industrial",

    // /planta/dashboard/page.tsx
    dbBackToBrands: "← Volver a Marcas",
    dbVisionTitle: "Visión del Imperio",
    dbProductionGroups: "Líneas / Grupos de Producción",
    dbGroupNamePlaceholder: "Nombre de la línea o grupo",
    dbSaveChanges: "Guardar Cambios",
    dbCreateGroup: "Crear Grupo",
    dbCancel: "Cancelar",
    dbLoading: "Cargando...",
    dbNoGroups: "No hay grupos creados.",
    dbEdit: "Editar",
    dbDelete: "Eliminar",
    dbNoGroup: "Sin Grupo",
    dbInspect: "Inspeccionar",
    dbShowVars: "Ver Variables",
    dbHideVars: "Ocultar Variables",
    dbVariables: "Variables",
    dbColName: "Nombre",
    dbColValue: "Valor",
    dbNoVars: "Sin variables disponibles",
    dbGlobalVision: "Visión Global",
    dbGlobalVisionDesc: "Monitoreo panóptico de reliquias y nodos sincronizados en tiempo real",
    dbNoPlcs: "Sin Reliquias Conectadas",
    dbNoPlcsDesc: "Todavía no hay conexiones físicas con equipos industriales. Solo los usuarios administradores pueden visualizar la maqueta de simulación.",
    dbAlertsTitle: "Registro de Alertas y Anomalías",
    dbColTime: "Hora",
    dbColEquip: "Equipo/Nodo",
    dbColCode: "Código",
    dbColDesc: "Descripción",
    dbColSeverity: "Severidad",
    dbClearErrors: "Borrar todos los errores",
    dbResolved: "Resuelto",
    dbConfirmDelete: "¿Seguro que deseas borrar este PLC? Esta acción es permanente y no se puede deshacer.",
    dbConfirmClearErrors: "¿Seguro que deseas borrar todos los errores? Esta acción no se puede deshacer.",
    dbConfirmDeleteGroup: "¿Eliminar este grupo/linea?",
  },
  EN: {
    loginTitle: "Login",
    forgotPassword: "Forgot your password?",
    choosePlan: "Choose your Plan",
    choosePlanDesc: "Select the subscription that best fits your needs to access the system.",
    planBasicAccess: "Access to Expert AI",
    planBasicLimit: "Limit of 20 questions per day",
    startFree: "Start for Free",
    planProAccess: ["Unlimited", "access", "to Expert AI"],
    planProPlcs: ["Connect up to", "2 PLCs", "in Plant AI"],
    planProSupport: "Priority support",
    subscribe: "Subscribe",
    freeAccessPlan: "Free Access",
    planEntAccess: ["Full and", "unlimited access", "to the system"],
    planEntPlcs: ["Connect", "unlimited PLCs", ""],
    fullAccess: "Full Access",
    // HOME
    activeSession: "Active Session",
    planWord: "PLAN",
    operatorLabel: "Operator:",
    adminPanel: "Admin Panel",
    changePlan: "Change Plan",
    logout: "Sign Out",
    infoBtn: "Info",
    freeAccessBadge: "✓ FREE ACCESS",
    requiresProBadge: "🔒 REQUIRES PRO",
    enterChat: "Enter Chat →",
    enterControl: "Enter Control →",
    loginAbove: "Sign in ↑",
    accessControl: "Access Control",
    operatorId: "Operator ID...",
    accessCode: "Access Code...",
    emailAddress: "Email address...",
    password: "Password...",
    enter: "Login",
    register: "Register",
    registering: "Registering...",
    registerNow: "Create an Account",
    hasAccount: "Already have an account?",
    backToLogin: "Back to login",
    loginError: "⚠ Incorrect email or password.",
    registerError: "⚠ Error registering account.",
    active: "Active",
    registerOperator: 'Operator Registration',
    operatorName: 'Operator Name',
    operatorNamePlaceholder: 'e.g. John D.',
    registerAction: 'Register',
    backToHome: 'Back to Home',
    fillAllFields: 'Please fill all fields.',
    passwordRequirements: 'Password must be at least 6 characters (including numbers), 1 uppercase, and 1 special symbol (#$%&).',
    redirecting: 'Redirecting to system...',
    emailPlaceholder: 'operator@example.com',
    passwordPlaceholder: '6 chars, 1 number, 1 upper, 1 symbol',
    iaExpert: "Expert AI (Manuals)",
    iaExpertDesc: "Superintelligence Assistant based on your company's official manuals. Solves operational doubts based on saved knowledge.",
    openChat: "Open Chat",
    comingSoon: "Coming Soon",
    iaPlant: "Plant AI (PLC Connection)",
    iaPlantDesc: "Predictive real-time analytical monitoring connected to sensors. Autonomously detects possible failures and anomalies in machines.",
    inDevelopment: "In development...",
    footer: "© 2026 Azteq-IA. Next-Generation Operating System.",
    
    // INFO MODAL
    infoTooltip: "What does each AI do?",
    iaExpertSubtitle: "Technical Assistant (RAG)",
    iaExpertFeat1: "Zero Hallucinations:",
    iaExpertFeat1Desc: "100% reliable answers based exclusively on *your* manuals and diagrams (PDF/TXT). Solve your problems safely.",
    iaExpertFeat2: "Boost your OEE (Downtime Killer):",
    iaExpertFeat2Desc: "Forget hours searching on paper. Diagnose and resolve complex faults in seconds, increasing your Pure Availability by up to 40%.",
    iaExpertFeat3: "Integrated Mathematical Expert:",
    iaExpertFeat3Desc: "Advanced calibration and control engineering calculations solved instantly and accurately.",
    iaPlantSubtitle: "IoT Monitoring & Digital Twin",
    iaPlantFeat1: "Connect with any PLC:",
    iaPlantFeat1Desc: "Native compatibility without paying extra licenses. Link Siemens, Modbus or Allen-Bradley equipment in just a few clicks.",
    iaPlantFeat2: "Grow at your own pace:",
    iaPlantFeat2Desc: "From automating a single machine to having a multi-brand fleet in your digital twin. Fits perfectly into your budget.",
    iaPlantFeat3: "Your plant in your pocket:",
    iaPlantFeat3Desc: "Live managerial dashboards. Monitor critical KPIs (pressures, bottlenecks) from your phone or tablet anywhere in the world.",
    
    // PLANES
    planesTitle: "Upgrade your Plan",
    planesDesc: "Select the subscription that best fits your needs. Upgrades are applied immediately to your account.",
    backBtn: "Back",
    subscriptions: "SUBSCRIPTIONS",
    monthly: "Monthly Billing",
    annual: "Annual Billing",
    save10: "Save 10%",
    currentPlan: "Your Current Plan",
    recommended: "Recommended",
    basicPlan: "Basic",
    proPlan: "Professional",
    enterprisePlan: "Enterprise",
    perMonth: "USD /mo",
    billedAnnually: "USD billed annually",
    unlockPro: "Unlock Pro Plan \u2192",
    contactSales: "Contact Sales",
    upgradePro: "Upgrade to Pro",
    buyEnterprise: "Get Enterprise",
    checkoutTitle: "Secure Checkout",
    checkoutDesc: "You are one step away from activating your subscription",
    totalToday: "Total to pay today",
    paySecure: "Pay Securely",
    connectingTerminal: "Connecting to payment terminal...",
    retryPayment: "Retry Payment",
    paymentFailed: "Payment Declined",
    paymentErrorDesc: "We're sorry, the payment connection failed or the card was declined. Please try again or contact support.",

    // CHAT
    newChat: "New Chat",
    viewChats: "View Chats",
    returnBtn: "Return",
    expertBadge: "Azteq-IA Expert",
    hello: "Hello! I am your Superintelligence AI",
    helloDesc: "",
    thinking: "Thinking...",
    placeholder: "Ask whatever you want...",
    send: "Send",
    errorCon: "⚠ Failed to connect to the chat API.",
    noRecentChats: "No recent chats",
    attachImage: "Attach image",

    // PLANTA [brand]/page.tsx
    plDisconnect: "Disconnect",
    plBackToBrands: "Back to Brands",
    plControlCenter: "Control Center",
    plPlcConnection: "PLC Connection",
    plDashboard: "Dashboard",
    plRitualLink: "Link Setup",
    plConnectingTo: "Connecting to",
    plLocalMode: "Local Network (LAN)",
    plCloudMode: "Cloud Tunnel (VPN)",
    plSelectPlc: "Select Saved Device / New Connection",
    plNewConnection: "-- Create New Connection --",
    plConnectionPaths: "Connection Paths",
    plLocalModeDesc: "The Azteq-IA device connects on the same local network (LAN) as the",
    plCloudModeDesc: "Communication travels through an encrypted VPN tunnel provided by the network administrators.",
    plReadMore: "Read more: Step-by-step connection guide",
    plControllerFamily: "Controller Family / Protocol",
    plVpnNote: "The IP must belong to the encrypted VPN tunnel, not the factory's local network (LAN).",
    plIpLocal: "Device IP (LAN)",
    plIpVpn: "Tunnel IP (VPN)",
    plPortLabel: "Access Port",
    plRackLabel: "Level (Rack)",
    plSlotLabel: "Slot",
    plConnecting: "CONNECTING...",
    plConnect: "ESTABLISH LINK",
    plRealTimeMonitoring: "REAL-TIME MONITORING",
    plConnectionStatus: "Connection Status",
    plCpuTemp: "CPU Temperature",
    plSystemPressure: "System Pressure",
    plGeneralStatus: "General Status",
    plCyclesPerHour: "Cycles / Hour",
    plAccessError: "⚠ PLC Access Error",
    plPredictiveAlarm: "Predictive Alarm",
    plAllNormal: "shows no anomalies in the last reading. Running at 98% capacity.",
    plAdjustIO: "Adjust I/O",
    plSaveName: "Name to save...",
    plSave: "SAVE",
    plLiveAssistant: "Live assistant connected to",
    plAiGreeting: "Hello. I am Azteq's AI connected to",
    plAiGreetingEnd: ". How can I help you?",
    plAnalyzing: "Analyzing...",
    plChatPlaceholder: "Ask about the",
    plVarMapper: "Free Variable Mapper",
    plHideHelp: "Hide Help",
    plHowItWorks: "How does it work?",
    plNewSignal: "Link New PLC Signal",
    plGroupCol: "Group/Routine",
    plLabelCol: "Logical Tag",
    plAddressCol: "Address",
    plUnitCol: "Unit",
    plDataTypeCol: "Data Type",
    plActionCol: "Action",
    plNoMappings: "[ NO MAPPINGS FOUND ]",
    plAddVarsHint: "Add variables above to start the digital twin.",
    plCancel: "Cancel",
    plSaveMap: "Seal & Save Map",

    // /planta/page.tsx
    piBack: "← Back",
    piHelp: "Help",
    piIaPlanta: "Plant AI",
    piOpenDashboard: "Open Global Vision (Dashboard)",
    piSelectPLC: "Select PLC",
    piSelectPLCDesc: "Choose the manufacturer of the programmable logic controller the Plant AI should connect to and analyze individually.",
    piIndustrialConnection: "Industrial Connection",

    // /planta/dashboard/page.tsx
    dbBackToBrands: "← Back to Brands",
    dbVisionTitle: "Empire Vision",
    dbProductionGroups: "Production Lines / Groups",
    dbGroupNamePlaceholder: "Line or group name",
    dbSaveChanges: "Save Changes",
    dbCreateGroup: "Create Group",
    dbCancel: "Cancel",
    dbLoading: "Loading...",
    dbNoGroups: "No groups created.",
    dbEdit: "Edit",
    dbDelete: "Delete",
    dbNoGroup: "No Group",
    dbInspect: "Inspect",
    dbShowVars: "Show Variables",
    dbHideVars: "Hide Variables",
    dbVariables: "Variables",
    dbColName: "Name",
    dbColValue: "Value",
    dbNoVars: "No variables available",
    dbGlobalVision: "Global Vision",
    dbGlobalVisionDesc: "Panoptic monitoring of synced devices and nodes in real time",
    dbNoPlcs: "No Connected Devices",
    dbNoPlcsDesc: "No physical connections with industrial equipment yet. Only admin users can view the simulation mockup.",
    dbAlertsTitle: "Alerts & Anomalies Log",
    dbColTime: "Time",
    dbColEquip: "Device/Node",
    dbColCode: "Code",
    dbColDesc: "Description",
    dbColSeverity: "Severity",
    dbClearErrors: "Clear all errors",
    dbResolved: "Resolved",
    dbConfirmDelete: "Are you sure you want to delete this PLC? This action is permanent and cannot be undone.",
    dbConfirmClearErrors: "Are you sure you want to clear all errors? This action cannot be undone.",
    dbConfirmDeleteGroup: "Delete this group/line?",
  }
};

type ContextType = {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: typeof dictionary['ES'];
};

const LanguageContext = createContext<ContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('ES');
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: dictionary[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
